server:
  port: 8081
spring:
  config:
    import: optional:file:.env[.properties]
    ##import: "optional:classpath:.env"
  datasource:
      url: jdbc:mysql://capDB.cbk6kgck2fjy.ap-northeast-2.rds.amazonaws.com:3306/capDB
      username: ${MYSQL_USER}
      password: ${MYSQL_PW}
      driver-class-name: com.mysql.cj.jdbc.Driver




  servlet:
    multipart:
      enabled: true
      maxFileSize: 200MB
      maxRequestSize: 300MB
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
openai:
  model: gpt-4o
  api:
    key: ${OpenAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
